import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    paddingTop: 44,
    paddingBottom: 48,
    paddingHorizontal: 44,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#0f172a",
    backgroundColor: "#ffffff",
  },
  reportHeader: {
    marginBottom: 14,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  reportHeaderTop: {
    marginBottom: 6,
  },
  profileChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#dbe4ef",
    borderRadius: 999,
    backgroundColor: "#f8fafc",
  },
  profileAvatar: {
    width: 28,
    height: 28,
    borderRadius: 999,
    objectFit: "cover",
    borderWidth: 1,
    borderColor: "#dbe4ef",
  },
  profileAvatarPlaceholder: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#dbe4ef",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarInitials: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#64748b",
  },
  profileName: {
    fontSize: 8,
    color: "#334155",
    textAlign: "left",
    maxWidth: 130,
  },
  reportTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 18,
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  reportSubtitle: {
    fontSize: 11,
    color: "#475569",
    marginBottom: 6,
  },
  reportMeta: {
    fontSize: 8.5,
    color: "#64748b",
    marginBottom: 4,
  },
  reportNote: {
    fontSize: 8.5,
    color: "#64748b",
    lineHeight: 1.35,
    maxWidth: 430,
  },
  dayBlock: {
    marginBottom: 14,
    borderLeftWidth: 2,
    borderLeftColor: "#6f94c0",
    paddingLeft: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  dayTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 11,
    marginBottom: 7,
    color: "#0f172a",
  },
  dayTable: {
    borderWidth: 1,
    borderColor: "#dbe4ef",
    borderRadius: 6,
    overflow: "hidden",
    marginLeft: 2,
  },
  slotRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e8eef6",
  },
  slotLabel: {
    width: "33%",
    fontSize: 8.2,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#475569",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: "#e8eef6",
  },
  slotBody: {
    fontSize: 9.5,
    lineHeight: 1.4,
    color: "#1e293b",
    width: "67%",
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  slotMeta: {
    marginTop: 3,
    fontSize: 8,
    lineHeight: 1.35,
    color: "#64748b",
  },
  emptyMonthBox: {
    marginTop: 8,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
  },
  emptyMonthTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
    marginBottom: 6,
    color: "#0f172a",
  },
  emptyMonthText: {
    fontSize: 10,
    lineHeight: 1.5,
    color: "#334155",
  },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 44,
    right: 44,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
  },
});
